SmartMonitorAdmin/Controllers/UserController.cs
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {
            //var items = await SmartMonitorDataManager<User>.GetItemsAsync(d => !d.Completed);
            List<User> items = BlobTable<User>.GetAllItems();

            return View(items);
        }
    }
}

SmartMonitorAdmin/Controllers/UserGroupController.cs
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class UserGroupController : Controller
    {
        // GET: UserGroup
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {
            //var items = await SmartMonitorDataManager<UserGroup>.GetItemsAsync(d => !d.Completed);
            List<UserGroup> items = await Task.Run(()=>BlobTable<UserGroup>.GetAllItems());

            return View(items);
        }
    }
}

SmartMonitorAdmin/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class UserManagementController : Controller
    {
        // GET: UserManagement
        public ActionResult Index()
        {
            return View();
        }
    }
}

SmartMonitorAdmin/Views/UserManagement/Index.cshtml
@{
    ViewBag.Title = "User Management";
}

<div class="main-content clear-float">
    <div class="tile-area no-padding">
        <div class="tile bg-white tile-big-x" data-role="tile">
            <div class="tile-content">
                <div class="panel" style="height: 100%;vertical-align:middle;align-content:center;border:ridge">
                    <div class="heading bg-darkBlue fg-white"><span class="title text-light" style="font-weight:bold">User Groups</span></div>
                    <div class="content fg-dark clear-float">
                        <a href="@Url.Action("Index", "UserGroup")">
                            <span class="mif-users icon mif-4x"></span>
                            <span style="font-size:medium;font-weight:bold;vertical-align:text-top">Manage User Groups</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="tile bg-white tile-big-x" data-role="tile">
            <div class="tile-content">
                <div class="panel" style="height: 100%;vertical-align:middle;align-content:center;border:ridge">
                    <div class="heading bg-darkBlue fg-white"><span class="title text-light" style="font-weight:bold">Users</span></div>
                    <div class="content fg-dark clear-float">
                        <a href="@Url.Action("Index", "User")">
                            <span class="mif-user icon mif-4x"></span>
                            <span style="font-size:medium;font-weight:bold;vertical-align:text-top">Manage Users</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>