SmartMonitorAdmin/Controllers/GpsTrackingController.cs
using Scf.Net.Base;
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using SmartMonitorMessages;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class GpsTrackingController : Controller, IEventFeedback, IEventReceiver
    {
        private GpsMap _mapData = new GpsMap();
        private static BlobQueue _gpsQueue = null;

        public GpsTrackingController()
        {
            if (_gpsQueue == null)
            {
                _gpsQueue = new BlobQueue("gpsmessages", ConfigurationManager.AppSettings["BlobStorageConnectionString"], this, this);
                _gpsQueue.Initialize();
            }
        }
        
        // GET: GpsTracking
        public ActionResult Index()
        {
            return View(_mapData);
        }

        [HttpPost]
        public JsonResult Refresh()
        {

            return Json(_mapData, JsonRequestBehavior.AllowGet);
        }


        public bool OnMessage(object sender, ReceivedMessageEventArgs args)
        {
            GpsMessage msg = args.Message as GpsMessage;
            if (msg != null)
            {
                _mapData.UpdateLocation(msg.DeviceId, msg.Latitude, msg.Longitude);
            }

            //RedirectToAction("Index", "GpsTracking");
            return true;
        }

        public void OnComplete(object sender, TaskEventArgs args)
        {

        }

        public void OnError(object sender, InternalErrorEventArgs args)
        {

        }

        public void OnException(object sender, Exception ex)
        {

        }
    }
}

SmartMonitorAdmin/Controllers/ImageController.cs
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace SmartMonitorAdmin.Controllers
{
    public class ImageController : Controller
    {
        private string containerName = "images";
        // GET: Image
        public ActionResult Index()
        {            
            return View(BlobContent.ListImages(containerName));
        }

        public ActionResult Add()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Save()
        {            
            foreach (string name in Request.Files)
            {
                var file = Request.Files[name];

                string fileName = System.IO.Path.GetFileName(file.FileName);

                BlobContent.UploadImage(containerName, fileName);

                //string imagename = file.FileName;
                //int index = imagename.IndexOf('.');
                //imagename = (index > 0) ? imagename.Substring(0, index) : imagename;
                //imagename = imagename.Replace(' ', '_');

                //Image image = new Image(imagename, fileName, Request["description"]);

                //ImageDataManager.Add(image, file);
            }
            return HttpNotFound();
        }

    }
}

SmartMonitorAdmin/Controllers/ParameterController.cs
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class ParameterController : Controller
    {
        // GET: Parameter
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {
            //var items = await SmartMonitorDataManager<Parameter>.GetItemsAsync(d => !d.Completed);
            List<Parameter> items = BlobTable<Parameter>.GetAllItems();
            return View(items);
        }

        [ActionName("Create")]
        public async Task<ActionResult> CreateAsync()
        {
            return PartialView();
        }

        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind(Include = "Id,Name,Units,Serial,Type,LogToDatabase,MonitoringInterval, MonitoringIntervalType, Description,Completed")] Parameter item)
        {
            if (ModelState.IsValid)
            {
                //await SmartMonitorDataManager<Parameter>.CreateItemAsync(item);
                BlobTable<Parameter>.Upsert(item.Id, item);
                return RedirectToAction("Index");
            }

            return PartialView(item);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync([Bind(Include = "Id,Name,Units,Serial,Type,LogToDatabase,MonitoringInterval, MonitoringIntervalType,Description,Completed")] Parameter item)
        {
            if (ModelState.IsValid)
            {
                //await SmartMonitorDataManager<Parameter>.UpdateItemAsync(item.Id, item);
                BlobTable<Parameter>.Upsert(item.Id, item);

                return RedirectToAction("Index");
            }

            return PartialView(item);
        }

        [ActionName("Edit")]
        public async Task<ActionResult> EditAsync(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Parameter item = await SmartMonitorDataManager<Parameter>.GetItemAsync(id);
            Parameter item = BlobTable<Parameter>.GetItem(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return PartialView(item);
        }

        [ActionName("Delete")]
        public async Task<ActionResult> DeleteAsync(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Parameter item = await SmartMonitorDataManager<Parameter>.GetItemAsync(id);
            Parameter item = BlobTable<Parameter>.GetItem(id);

            BlobTable<Parameter>.Delete(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return PartialView(item);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmedAsync([Bind(Include = "Id")] string id)
        {
            //await SmartMonitorDataManager<Parameter>.DeleteItemAsync(id);
            Scf.Net.BlobStorage.BlobTable<Parameter>.Delete(id);
            return RedirectToAction("Index");
        }

        [ActionName("Alarms")]
        public async Task<ActionResult> AlarmsAsync(string id)
        {
            Parameter item = null;

            //item = await SmartMonitorDataManager<Parameter>.GetItemAsync(id);
            item = BlobTable<Parameter>.GetItem(id);
            item.Alarms = BlobTable<Alarm>.GetAllItems();
            item.Alarms = item.Alarms.FindAll(x => x.DeviceId == id);
            ViewData["parameterId"] = item.Id;

            return (item != null) ? PartialView(item.Alarms) : PartialView();
        }

        [HttpPost]
        public ActionResult SaveAlarms(string id, Alarm[] alarms)
        {
            Parameter item = null;
            ViewData["parameterId"] = id;

            //Task.Run(async () =>
            //{
                //item = await SmartMonitorDataManager<Parameter>.GetItemAsync(id);
                item = BlobTable<Parameter>.GetItem(id);

            if (item != null)
            {
                if (item.Alarms != null)
                    item.Alarms.Clear();
                else
                    item.Alarms = new List<Alarm>();

                foreach (Alarm alarm in alarms)
                {
                    alarm.DeviceId = item.Id;
                    item.Alarms.Add(alarm);
                    BlobTable<Alarm>.Upsert(alarm.Id, alarm);
                }
            }
            //}).Wait();

            return RedirectToAction("Index");
        }
    }
}

SmartMonitorAdmin/Controllers/SmartDeviceController.cs
using Microsoft.Azure.Devices;
using Microsoft.Azure.Devices.Common.Exceptions;
using Scf.Net.BlobStorage;
using SmartMonitorAdmin.Data;
using SmartMonitorAdmin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SmartMonitorAdmin.Controllers
{
    public class SmartDeviceController : Controller
    {
        // GET: SmartDevice
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {
            //var items = await SmartMonitorDataManager<SmartDevice>.GetItemsAsync(d => !d.Completed);
            List<SmartDevice> items = BlobTable<SmartDevice>.GetAllItems();
            return View(items);
        }

        [ActionName("Create")]
        public async Task<ActionResult> CreateAsync()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind(Include = "Id,Name,UserId,DeviceId,DeviceKey,Description,SerialNumber,Platform, Manufacturer, Model,GpsTracking,Latitude,Longitude,Completed")] SmartDevice item)
        {
            if (ModelState.IsValid)
            {
                await CreateIoTDevice(item);
                BlobTable<SmartDevice>.Upsert(item.Id, item);
                //await SmartMonitorDataManager<SmartDevice>.CreateItemAsync(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync([Bind(Include = "RowKey,Name,UserId,DeviceId,DeviceKey,Description,SerialNumber,Platform, Manufacturer, Model,GpsTracking,Latitude,Longitude,Completed")] SmartDevice item)
        {
            if (ModelState.IsValid)
            {
                //await SmartMonitorDataManager<SmartDevice>.UpdateItemAsync(item.Id, item);
                BlobTable<SmartDevice>.Upsert(item.Id, item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        [ActionName("Edit")]
        public async Task<ActionResult> EditAsync(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //SmartDevice item = await SmartMonitorDataManager<SmartDevice>.GetItemAsync(id);
            SmartDevice item = BlobTable<SmartDevice>.GetItem(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        [ActionName("Delete")]
        public async Task<ActionResult> DeleteAsync(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //SmartDevice item = await SmartMonitorDataManager<SmartDevice>.GetItemAsync(id);
            SmartDevice item = BlobTable<SmartDevice>.GetItem(id);

            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmedAsync([Bind(Include = "Id")] string id)
        {
            //await SmartMonitorDataManager<SmartDevice>.DeleteItemAsync(id);
            BlobTable<SmartDevice>.Delete(id);

            return RedirectToAction("Index");
        }

        [ActionName("Details")]
        public async Task<ActionResult> Details(string id)
        {
            //var item = await SmartMonitorDataManager<SmartDevice>.GetItemAsync(id);
            SmartDevice item = BlobTable<SmartDevice>.GetItem(id);

            return PartialView(item);
        }

        private async Task<string> CreateIoTDevice(SmartDevice item)
        {
            string deviceKey = "";
            var registryManager = RegistryManager.CreateFromConnectionString(ConfigurationManager.AppSettings["IoTHubConnectionString"]);
            try
            {
                item.DeviceId = Guid.NewGuid().ToString();
                var device = await registryManager.AddDeviceAsync(new Device(item.DeviceId));

                item.DeviceKey = device.Authentication.SymmetricKey.PrimaryKey;
            }
            catch (DeviceAlreadyExistsException)
            {
            }

            return deviceKey;
        }
    }
}

SmartMonitorAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Smart Monitor Administration</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <style>
        html {
            width: 100%;
            height: 100%;
            display: table;
        }

        body {
            width: 100%;
            display: table-cell;
            font-family: "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;
            font-size: 12px;
            font-style: normal;
            font-variant: normal;
            font-weight: 400;
            line-height: 12px;
        }

        html, body {
            margin: 0px;
            padding: 0px;
        }

        table, th, td {
            border: 1px solid groove;
        }
    </style>

</head>
<body class="metro">
    <div class="inner">
        <div class="row" style="background-color:cornflowerblue">
            <div class="col-lg-12 fg-white v-align-middle align-center">
                <span class="mif-earth2 icon mif-3x padding10 v-align-top-text">  Smart Monitor Admin Dashboard</span>                
            </div>
        </div>
        <hr />
        <div class="row">
         <div class="table-responsive col-lg-12">
            <table style="width:100%">
                <tr>
                    <td valign="top" align="left" style="width:20%;padding-right:5px">
                        <ul class="sidebar" style="background-color:cornflowerblue">
                            <li>
                                <a href="@Url.Action("Index", "Home")">
                                    <span class="mif-home icon"></span>
                                    <span class="title">Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Account")">
                                    <span class="mif-organization icon"></span>
                                    <span class="title">My Account</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "UserManagement")">
                                    <span class="mif-users icon"></span>
                                    <span class="title">User Management</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "SmartDevice")">
                                    <span class="mif-mobile icon"></span>
                                    <span class="title">Device Management</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "GpsTracking")">
                                    <span class="mif-location icon"></span>
                                    <span class="title">GPS Tracking</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Parameter")">
                                    <span class="mif-feed icon"></span>
                                    <span class="title">Device Monitoring</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Communication")">
                                    <span class="mif-contacts-dialer icon"></span>
                                    <span class="title">Communication</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "GeneralSettings")">
                                    <span class="mif-cogs icon"></span>
                                    <span class="title">Settings</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Image")">
                                    <span class="mif-file-image icon"></span>
                                    <span class="title">Images</span>
                                </a>
                            </li>
 
                        </ul>
                    </td>
                    <td valign="top" align="left" style="padding-left:5px">
                        @RenderBody()
                    </td>
                </tr>
            </table>
        </div>
        </div>  
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>